# Generated by Django 5.2.7 on 2025-10-19 04:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhc', models.CharField(max_length=20, unique=True, verbose_name='NHC')),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Estable', 'Estable'), ('Delicado', 'Delicado'), ('Recuperación', 'Recuperación')], default='Estable', max_length=20)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='gestion.especialidad')),
            ],
        ),
    ]
